### ISSUE TITLE
Architect 10 breaking change list

### ISSUE THREAD

**Issue by ryanblock** [architect/architect#1233]
We don't currently have a timeline for shipping Arc 10 (probably early next year, if I were to guess), but this issue is just to collect the various breaking changes we'll make so we don't forget any tidying along the way.

- [x] Default Lambda architecture from `x86_64` to `arm64` (assuming it's rolled out everywhere by 10 release time and hasn't experienced any major issues)
  - See https://github.com/architect/architect/issues/1304
- [x] Default Lambda runtime from `nodejs14.x` to `nodejs16.x` (which will hopefully be out + stable by then)
  - Doesn't look like that's going to be the case, but if so I'll make it happen!
- [x] Deprecate use of `NODE_ENV` in favor of `ARC_ENV`
- [x] Deprecate use of `ARC_CLOUDFORMATION` env var
- [x] Deprecate use of `ARC_HTTP` env var
- [x] Deprecate the [CORS env var / middleware](https://github.com/architect/sandbox/blob/main/src/http/middleware/_cors.js#L3) in Sandbox
- [x] Add `ARC_*` namespaced alternative env vars to all main Architect environment variables
  - Not a breaking change now, but tees up a breaking change for non-namespaced env vars down the road
- [x] Add [automatic port selection to Sandbox services + Functions]( https://github.com/architect/architect/issues/1233#issuecomment-1019400675)
- [x] Cut Sandbox + ASAP over to using [`ARC_STATIC_BUCKET` env var](https://github.com/architect/sandbox/blob/main/src/invoke-lambda/env.js#L62-L71) for the local static asset folder path
- [x] Fully cut Arc Functions calls over to AWS service mocks
  - [x] Retire Sandbox [`/__arc`](https://github.com/architect/sandbox/blob/main/src/http/register-websocket/index.js#L20-L21) (and other code paths), see https://github.com/architect/architect/issues/1204
    - Fixed in https://github.com/architect/sandbox/pull/668/ (https://github.com/architect/sandbox/pull/668/commits/2a4f4361f09912aebd073d8d4d47152dcf6a9d95)
  - ~SQS/SNS~ – probably out of scope for this release, will have to build that later
- [x] `--static` flag in `@architect/create`
- [x] `--nuke` flag in `@architect/logs`
- [x] `@indexes` to be phased out in favor of `@tables-indexes` (but still fully forward-compatible)
- [x] `@macros` to be phased out in favor of `@plugins` (but still fully forward-compatible)
- [x] Stop publishing all packages to GitHub Package registry
- [x] Deprecate `toml` support in Architect Parser (see #1294)
- [x] Per [CLIG, deprecate CLI args used as flags](https://clig.dev/#arguments-and-flags), generally prefer flags wherever possible
- [x] Remove `arc package` command (in favor of `arc deploy --dry-run` or the new `arc deploy --eject`)

### Arc Functions
- [x] Retire [WebSockets use of `/__arc`](https://github.com/architect/functions/blob/main/src/ws/send-sandbox.js#L20)
  - Fixed in https://github.com/architect/functions/pull/513/ (https://github.com/architect/functions/pull/513/commits/bd35f89a3ac1b0b80620d583d45cd4e5cf9a2c12)
- [x] Remove all legacy Arc v5 code paths from Arc Functions
  - [x] [`events`](https://github.com/architect/functions/blob/main/src/events/index.js#L20-L25)
  - [x] [`queues`](https://github.com/architect/functions/blob/main/src/queues/index.js#L20-L25)

Some other good candidates [here](https://github.com/search?q=org%3Aarchitect+TODO+%5Bremove%5D&type=code) + [here](https://github.com/search?q=org%3Aarchitect+TODO+%5Bdeprecate%5D&type=code)

Of course, anything here is up for debate – I fully expect we'll add to and prune this list plenty before 10 ships.

**Comment by reconbot** [comment]
I'd like to clean up port selection. Right now we do math on env vars for some ports, and have default values for others. I think even our docs are wrong for one of them. I'd like to propose making arc/functions less smart (no defaults, always requiring configuration), and removing any dependencies between ports. It's currently confusing to operate in tests and as plugins start to add more services this will start to be a bigger issue.

In arc/sandbox, I'd like to propose default values and env overrides for all services. With no relation between them. (eg no math). For programmatic sandbox access, I'd like options to override the defaults on the start methods.

In arc/functions the executed lambda's would have the correct env vars when run in staging/production or the sandbox. However arc/functions also get called in tests against a programmatically started sandbox, so we need to ensure that sandbox and function env vars match, and that functions complain helpfully when they're missing needed env vars. Right now we fall back to default values, but I don't know when this would be needed. Missing env vars would be an error in sandbox and staging/production.

**Comment by reconbot** [comment]
Another breaking change I would like, is to be able to disable the `sandbox-startup` from preferences.arc when starting the sandbox programmatically. It's wonderful to have in local development but not needed in tests.

**Comment by ryanblock** [comment]
Disabling `@sandbox-startup` will be an [opt-in API option](https://github.com/architect/sandbox/pull/659/commits/ca39c880dbee927c576c514afbe587b886f7e647) starting in Sandbox 4.3 / Arc 9.3.

**Comment by ryanblock** [comment]
Re. port selection:

> I'd like to clean up port selection.

Good news, this landed for Sandbox v5! https://github.com/architect/sandbox/pull/668/commits/0f1ba94c951ce3ca452c86d66fe7b42836b4352b

> Right now we do math on env vars for some ports, and have default values for others. I think even our docs are wrong for one of them.

Yep, it's gross. Now port selection abides by the following behavior:
- `@http` defaults to `3333`; if `3333` is occupied, Sandbox will fail to start. I may make an opt-in to allow folks to automatically select the `@http` port, but the feedback I got here was that the web interface should be at a predictable port because of browser autocomplete, memory/expectations, etc.
- `@tables`, `@events`, `@queues`, `_arc` (internal services): all have different/new default ports, and on startup will try a bunch of times to find the next open port (without stepping on each others' toes). These ports are also each fully end-user configurable, and if a manually configured port happens to be occupied, Sandbox will fail to start.

While there are default ports under the hood, they should not be made use of in userland – userland will be supplied with the correct final ports (after automatic port selection) via env vars.

> I'd like to propose making arc/functions less smart (no defaults, always requiring configuration), and removing any dependencies between ports.

`@tables`, `@events`, `@queues`, `_arc` all do have (new) default ports. Those ports are not relevant to users, but are known and used in certain Architect-only test scenarios. The default ports should not be a concern of end users testing their apps but they can configure it themselves if desired.

And yes, there are no longer any inter-port dependencies.

> ... I'd like to propose default values and env overrides for all services. With no relation between them. (eg no math). For programmatic sandbox access, I'd like options to override the defaults on the start methods.

Yep! So there are default values and env overrides for all, no relation between any. I have been considering adding port selection via API; right now they are set via env vars or `prefs.arc`.

> In arc/functions the executed lambda's would have the correct env vars when run in staging/production or the sandbox. However arc/functions also get called in tests against a programmatically started sandbox, so we need to ensure that sandbox and function env vars match, and that functions complain helpfully when they're missing needed env vars.

Yep, did this!

> Right now we fall back to default values, but I don't know when this would be needed. Missing env vars would be an error in sandbox and staging/production, and errors would be helpful when setting up a testing environment.

Per above, they continue to fall back to default values (see above) for some internal testing needs (e.g. testing Arc Functions methods without running them in a live Sandbox).

**Comment by reconbot** [comment]
This is a beautiful thing 👏

**Comment by ryanblock** [comment]
All intended breaking changes are now live in Arc 10 RC4!
