### ISSUE TITLE
architect 6.x release master issue

### ISSUE THREAD

**Issue by brianleroux** [architect/architect#404]
Architect 6 is a big release. It represents a ground up rewrite to support for SAM based applications and deployment with AWS Cloudformation. 

In the process we were able to add some nice new additions: 

- a new cli tool https://github.com/architect/cli (try it out `npm i -g @architect/cli`)
- we broke packages into separate repos to facilitate reuse between local and global install
  - `architect/parser`
  - `architect/sandbox`
  - `architect/hydrate`
  - `architect/env` 
  - `architect/utils`
  - `architect/package`
  - `architect/deploy`
  - `architect/logs` 
  - `architect/repl`
  - `architect/cli`
- The kitchen sink is still available at https://github.com/architect/architect (for local install and classic npx based workflows `npm i @architect/architect`)

This closes a number of issues:
- [ ] https://github.com/architect/architect/issues/123
- [ ] https://github.com/architect/architect/issues/245
- [ ] https://github.com/architect/architect/issues/288
- [ ] https://github.com/architect/architect/issues/344
- [ ] https://github.com/architect/architect/issues/329
- [ ] https://github.com/architect/architect/issues/331
- [ ] https://github.com/architect/architect/issues/376
- [ ] https://github.com/architect/architect/issues/395

**Comment by ryanblock** [comment]
I know it is early, but I’d love to outline and discuss migration from Architect n to 6!

**Comment by brianleroux** [comment]
sounds good / me too. things I know:

- [x] `npx` commands mostly work the same as before 
- [x] global binary `arc` commands are based on same code
- [x] dynamodb access is way more locked down
- [x] `architect/data` now has a new method `reflect()` for getting a client; needed to be async so this is different; left the old sig in `3.x` but think we'll deprecate and make reflect() the main entry in `4.x` 

things that need investigation/discovery:

- [ ] http form posts
- [ ] http multipart form posts
- [ ] responding with binary content
- [ ] anything else we have solved w VTL might not be solved with aws_proxy style integration
- [ ] author new `sns` publish in `architect/functions`
- [ ] author new `sqs` publish in `architect/functions`
- [ ] verify `proxy` still works w `architect/functions`
- [ ] verify `http` still works w `architect/functions`
- [ ] verify `static` still works w `architect/functions`
- [ ] verify `scheduled` still works w `architect/functions`
- [ ] verify `tables` still works w `architect/functions`
- [ ] verify `ws` still works w `architect/functions`

think the upgrade story will be downstream all this and the issue triage above.

**Comment by brianleroux** [comment]
quick update: the new architect/functions has a v4 pr that has had a first pass of testing; backwards compatible other than moving `arc.middleware` to `arc.http.middleware` and `arc.proxy` to `arc.http.proxy`. next step is to start a docs pr.

**Comment by ryanblock** [comment]
Adding checklist from #396:
- [ ] use the smol packages in a 6.x branch 
- [ ] remove src/audit 
- [ ] remove src/config 
- [ ] remove src/create (!)
- [ ] upgrade src/deploy to new smol package
- [ ] upgrade src/dns (think @ryanblock wants to take a stab at this part)
- [ ] upgrade src/env  to new smol package
- [ ] update src/help
- [ ] update src/hydrate to new smol package
- [ ] remove src/init
- [ ] remove src/inventory
- [ ] update src/logs to new smol package
- [ ] update src/package to new smol package
- [ ] update src/repl to new smol package
- [ ] update src/sandbox to new smol package
- [ ] remove src/tags
- [ ] remove src/util
- [ ] remove src/version

**Comment by ryanblock** [comment]
Running list of Arc 6 launch requirements:
- [ ] arc.codes pass
- [ ] [Functions compat update](https://github.com/architect/functions/pull/56)
- [ ] [Sandbox compat update](https://github.com/architect/sandbox/pull/29)
- [ ] https://github.com/architect/repl/issues/1
- [ ] https://github.com/architect/deploy/issues/11
- [ ] https://github.com/architect/deploy/issues/10
- [ ] https://github.com/architect/logs/issues/4
- [ ] https://github.com/architect/architect/issues/417
- [ ] https://github.com/architect/utils/issues/8
- [ ] Quick pass on new help
- [ ] Deprecate `@architect/data` on npm
