### ISSUE TITLE
integration tests

### ISSUE THREAD

**Issue by filmaj** [architect/architect#421]
need to exercise the combination of using `package` and `deploy` and verifying infra on AWS exists as desired.

# TODO

- [x] need an AWS account / creds to run against; it's in the cli repo as travis ci env vars
- [ ] need to write test run `arc` package + deploy steps
- [ ] how to verify things on aws exist as desired? use `aws-sdk`?
- [ ] set benchmark of 5 mins on test run
- [ ] what about integrating arc/functions with both arc/sandbox as well as deployed to lambda to ensure it functions as desired?

**Comment by brianleroux** [comment]
closing for now. think we're in a good place (but can always improve) and always open to reopening of course!
